FROM maven:3.9.9-eclipse-temurin-24 AS build

WORKDIR /app

COPY pom.xml .
COPY product-service/pom.xml product-service/

RUN mvn dependency:go-offline -B

COPY product-service/src/ product-service/src/

RUN mvn clean package -DskipTests -pl product-service

FROM eclipse-temurin:24-jre-alpine

WORKDIR /app

COPY --from=build /app/product-service/target/*.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]